### ISSUE TITLE
The ModSpec is an OGC Policy document

### ISSUE THREAD

**Issue by cnreediii** [opengeospatial/ogc-modspec#9]
There are ambiguities and inconsistent usage of the terms "policy" and "standard". Historically, the ModSpec was developed in the OGC Policy SWG. The document was originally called a Policy Standard. However, for some reason, the SWG decided to call the ModSpec a "standard".

To eliminate the ambiguities and resulting confusion, the following are recommendations to be discussed and decided on:

Recommendation 1: This revision of the ModSpec shall be termed an OGC Policy. 
Recommendation 2: As appropriate, all references in the ModSpec to "standard" shall be replaced with "policy". Obviously, this is based on context!

See also issue 5.

**Comment by ronaldtse** [comment]
Thank you @cnreediii for raising this topic!

The ModSpec traditionally is used for two purposes in OGC:
1. As a policy stating that OGC standards need to be "modular" which means that requirement classes are the normative parts of its standards
2. As a specification of the information models for requirement classes, conformance classes, and the normative statements like requirements, recommendations and permissions (implied but not defined in the document).

There are other organizations that use the ModSpec, most prominently, ISO/TC 211, which adopts ModSpec "unofficially, but de facto". You can see these in the OGC-submitted documents like ISO 19170, or ones done by authors related to OGC like ISO 19115-3 and ISO 19135.

For other organizations that adopt ModSpec, they need the ModSpec object definitions to be in a "standard" instead of a "policy", since they would probably not be willing to "adopt an OGC Policy". 

It seems that there are at least two ways to achieve this cleanly:
1. Split ModSpec into two documents:
    * 1 OGC Policy that says "develop modular standards using the ModSpec models"
    * 1 OGC Standard that says "these are the specifications of the ModSpec models"
2. Say that an "OGC Policy is a type of OGC Standard"...? Still needs explanation for those organizations to justify why...

**Comment by heidivanparys** [comment]
@ronaldtse @jetgeo

I thought that ISO/TC 211 has ISO 19105 as a standard to conform to with regard to the “information model for requirements classes, etc.”?

**Comment by ronaldtse** [comment]
@heidivanparys is correct! The latest ISO 19105 does provide a basis for ISO/TC 211 standards’ requirements. 

However, its models are a minimal subset of ModSpec, so some standards in TC 211 adopt ModSpec fully (as a “superset” of 19105).  

On the other hand, the proposed models from ISO/TC 211/AHG 5 (after 19105) were more or less identical to ModSpec, so ModSpec does have a great influence.

**Comment by cnreediii** [comment]
One little "hiccough" that we will need to discuss and resolve is the model hierarchy. The current model has requirements classes consisting of one or more requirements modules. Unfortunately, this conflicts with other requirements related to conformance testing and recommendations. I suggest that a requirements module consists of one or more requirements classes. This resolves conflicts with other ModSpec requirements and is also in line with the Cambridge dictionary definition of "module".

Finally, I have always been uncomfortable if a reader/developer/editor most also procure an ISO document and read that document. Believe it or not, I have never read ISO 19105!

**Comment by cnreediii** [comment]
@ronaldtse Interesting conundrum WRT what to call this document - a standard or a policy. FYI, back in 2010 or so the Policy SWG termed the ModSpec a Policy Standard or some such :-)

Now, we do not need to have the word policy in the title. That said, the ModSpec does define a policy for the structure of a standard - which does not need to be an OGC standard.

**Comment by ronaldtse** [comment]
I share the same sentiment that the OGC ModSpec should not depend on any ISO document. It is unnecessary in any case, since the ModSpec models do not depend on ISO 19105.

I think a reasonable approach is to separate:
1. information model specifications of requirements etc.
2. policy of OGC

This would allow other organizations to use 1 without needing to deal with confusing terminology, spreading the OGC influence by reference.

**Comment by cnreediii** [comment]
@ronaldtse - Upon reflection, there may be a relatively simple way to implement 1 and 2 in a single document. First, we do not call the ModSpec a an OGC Policy document. Instead, we call the ModSpec a model for writing modular, testable standards. We then say that the ModSpec was developed and approved by the OGC but is a generic model that any SDO or other group can use as a model. We (OGC) then can state that the ModSpec document is approved separately as a required model for OGC Standards development and writing. This decision would be captured as a Policy directive but never mention in the actual ModSpec document. 

So, I would need to rewrite the preface and change all references to "Policy" to "this document" or "ModSpec" in the revision. 

Finally, I think for historical reasons and for the fact that ModSpec is in common usage that we keep the abbreviation  in the revision. We would then need to make such a statement in the preface.

This may sound a bit convoluted but is actually quite easy to implement!

**Comment by cnreediii** [comment]
@ronaldtse And some suggested wording for the Preface (and probably the Intro)

This OGC member developed and approved document defines a 
model and related requirements and recommendations for writing and 
structuring modular standards documents. Further, this model is designed
 to enable the consistent and verifiable testing of implementations of a
 standard that claim conformance.</p>

The goal is to ensure that a standard specifies 
requirements in a common and consistent manner and that these 
requirements are testable.

Note | For OGC only: Any new OGC Standard, abstract specification, or major  revision of an existing OGC Standard shall comply with the requirements  stated in this document.

**Comment by cnreediii** [comment]
Replaced by issue 37. Also part of Issue 8.
